STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A1_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A1_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-A1/50-1-A1_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts

STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A2_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A2_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-A2/50-1-A2_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts

STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A3_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/A3_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile //gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-A3/50-1-A3_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts

STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B1_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B1_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-B1/50-1-B1_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts

STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B2_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B2_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-B2/50-1-B2_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts

STAR --runThreadN 8 --genomeDir /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Sequence/STARIndex-2.7.9a --readFilesIn /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B3_R1_val_1.fq.gz /home/hs2256/palmer_scratch/Expt-50/human_mapping/trim_gallore_results/B3_R2_val_2.fq.gz --readFilesCommand zcat --sjdbGTFfile /gpfs/ycga/datasets/genomes/Homo_sapiens/Ensembl/GRCh38/Annotation/Genes/genes.gtf --outFileNamePrefix /home/hs2256/palmer_scratch/Expt-50/human_mapping/aligned_STAR/50-1-B3/50-1-B3_ --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM 10000000000 --quantMode TranscriptomeSAM GeneCounts